version: "3.9"
services:
  web:
    image: nginx
    volumes:
      - ./data/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - tileserver
      - routing
  app:
    image: node:18
    working_dir: /home/node/app
    volumes:
      - ./app:/home/node/app
    ports:
      - "9000:9000"
    user: "node"
    command: "yarn start"
    depends_on:
      - tileserver
      - routing
  tileserver:
    image: maptiler/tileserver-gl
    volumes:
      - ./data:/data
    ports:
      - "8282:8080"
    command: --port 8080 --config /data/config-tileserver.json --public_url http://localhost:8080/tiles --verbose
  routing:
    image: israelhikingmap/graphhopper
    volumes:
      - ./data:/data
    ports:
      - "8989:8989"
    command: --input /data/sources/brandenburg.osm.pbf --host 0.0.0.0 --config /data/config-graphhopper.yml
